# Generated by Django 5.2.13 on 2026-04-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_products_productviewhistory_product_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
